### ISSUE TITLE
Configure Hornet and Systemd Service

### ISSUE THREAD

**Issue by MrRo-de** [svenger87/hornet-alphanet-tutorial#3]
Hi, this part isn't working for me. 
cp /opt/hornet/hornet /opt/hornet-alphanet

shouldn't the path be called:
cp /opt/hornet /opt/hornet-alphanet

and i have to insert an -r option for cp. Cause i got the error that /opt/hornet is a folder and will be skipped.

but after i finished the tutorial with cp -r /opt/hornet /opt/hornet-alphanet
i couldn't start the hornet alphanet with
sudo systemctl start hornet-alphanet && journalctl -u hornet-alphanet -f

the journal gives me the error:
Jan 17 10:54:55 raspberrypi systemd[1]: Started Hornet Alphanet.
Jan 17 10:54:55 raspberrypi systemd[824]: hornet-alphanet.service: Failed to execute command: Permission denied
Jan 17 10:54:55 raspberrypi systemd[824]: hornet-alphanet.service: Failed at step EXEC spawning /opt/hornet-alphanet/hornet: Permission denied
Jan 17 10:54:55 raspberrypi systemd[1]: hornet-alphanet.service: Main process exited, code=exited, status=203/EXEC
Jan 17 10:54:55 raspberrypi systemd[1]: hornet-alphanet.service: Failed with result 'exit-code'.

**Comment by svenger87** [comment]
cp /opt/hornet/hornet /opt/hornet-alphanet is copying the hornet binary file to /opt/hornet-alphanet.

I don´t know what could be wrong here? Did you compile hornet? The file /opt/hornet/hornet should be there if you did,

**Comment by MrRo-de** [comment]
i repeated the command:
go build

and it exited with:
build github.com/gohornet/hornet: cannot find module for path crypto/ed25519

so there is no file /opt/hornet/hornet

**Comment by svenger87** [comment]
Seems you need to update your go installation.
```
wget https://golang.org/dl/go1.15.6.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.15.6.linux-amd64.tar.gz
export PATH=$PATH:/usr/local/go/bin```

**Comment by MrRo-de** [comment]
only as feedback:
the installation worked with the update from golang.

thank you
